title: The First Principles
description: Everything starts with The First Principles
author: Vignesh T.V.
theme: jekyll-theme-cayman
google_analytics: G-KJ7GS2K1GC


social-network-links:
  email: "vignesh@timecampus.com"
  facebook: tvvignesh
  github: tvvignesh
  twitter: techahoy
  patreon: timecampus
  youtube: /channel/UCLnTH4GOCB5fXWoOfgklQwA
  
