title: The First Principles
description: Everything starts with The First Principles
author: Vignesh T.V.
theme: jekyll-theme-cayman

social-network-links:
  email: "vignesh@timecampus.com"
  facebook: tvvignesh
  github: tvvignesh
  twitter: techahoy
  patreon: timecampus
  youtube: /channel/UCLnTH4GOCB5fXWoOfgklQwA
  
